In [16]:
#-*- coding : cp949 -*-
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By

import time
import urllib
#http://www.koreabaseball.com/Schedule/Game/BoxScore.aspx?leagueId=1&seriesId=1&gameId=20160324WOLG0&gyear=2016

In [25]:
browser = webdriver.Chrome(executable_path='/home/gohyunyoung98/바탕화면/Github/kbo_parsing/chromedriver')

browser.get('http://www.koreabaseball.com/Schedule/ScoreBoard/ScoreBoard.aspx')
browser.find_element_by_id('cphContainer_cphContents_btnPreDate').click()
browser.find_element_by_id('cphContainer_cphContents_btnPreDate').click()
#    element = WebDriverWait(browser,3).until(
#        EC.presence_of_element_located((By.ID,'cphContainer_cphContents_btnPreDate'))
#    )
#   element.click()

time.sleep(2)
btnList = browser.find_elements_by_css_selector('a[href^="/Schedule/Game/BoxScore.aspx?"]')
for i in range(len(btnList)):
    browser.find_elements_by_css_selector('a[href^="/Schedule/Game/BoxScore.aspx?"]')[i].click()
    time.sleep(2)
    
    #url=browser.current_url
    #박스스코어 화면
        
    html = browser.page_source
    soup = BeautifulSoup(html,'lxml')
    
    hName = soup.findAll('table.socreBoard th')
    
    
    
    
    browser.get('http://www.koreabaseball.com/Schedule/ScoreBoard/ScoreBoard.aspx')
    browser.find_element_by_id('cphContainer_cphContents_btnPreDate').click()
    browser.find_element_by_id('cphContainer_cphContents_btnPreDate').click()
    time.sleep(2)

In [64]:
print html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><link rel="shortcut icon" href="//image.koreabaseball.com/client/images/common/favicon.ico" /><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta name="keywords" content="kbo" /><meta name="author-date" content="20130308" /><meta http-equiv="x-ua-compatible" content="IE=9, Chrome" /><title>
	박스스코어 | 경기일정/결과 | KBO
</title><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/reset.css?version=201503111" /><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/common.css?version=20160310" /><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/jquery-ui.css" /><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/jquery.bxslider.css?version=20151006" />

	<script async="" src="//www.google-analytics.com/analytics.js"></script><script type="text/javascript" src="//image.koreabaseball.com/client/js/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="//image.koreabaseball.com/client/js/jquery-ui.js"></script>
	<script type="text/javascript" src="//image.koreabaseball.com/client/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="//image.koreabaseball.com/client/js/common.js?version=20150724"></script>
    <script type="text/javascript" src="//image.koreabaseball.com/client/js/rolling.js?version=20150305"></script>

    <link type="text/css" rel="stylesheet" href="http://image.koreabaseball.com/client/css/jquery-ui-theme.css?version=20150317" />
    <link type="text/css" rel="stylesheet" href="http://image.koreabaseball.com/client/css/sub.css?version=20150311" />
    <link type="text/css" rel="stylesheet" href="http://image.koreabaseball.com/client/css/games.css?version=20151029" />




    <script type="text/javascript">
        function setPlayerSearch() {
            var searchWord = encodeURI($('#txtSearchWord').val());

            if (searchWord != "") {
                location.href = "/Player/Search.aspx?searchWord=" + searchWord;
            }
        }
    </script>
    <script type="text/javascript">
        (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-15700655-14', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
    <form method="post" action="./BoxScore.aspx?leagueId=1&amp;seriesId=1&amp;gameId=20160327LTKT0&amp;gyear=2016" id="mainForm">
<div class="aspNetHidden">
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJNDA4MTc2ODc1D2QWAmYPZBYCZg9kFgICAw9kFgYCAQ8WAh4EVGV4dAUKM+yblCAyOOydvGQCAg8WAh4LXyFJdGVtQ291bnQCBBYIZg9kFgJmDxUECjE5ODgtMDMtMjgCODgb7J207JuF7Z2sIOy0neyerCDstpTrjIAgLi4uKu2UjOudvOyekCDtmLjthZTsl5DshJwg7Je066awIOq1rOuLqOyjvC4uLmQCAQ9kFgJmDxUECjIwMDEtMDMtMjgCMDEf7ZWc6rWt7JW86rWs7J2466qF7IKs7KCEIOuwnC4uLgBkAgIPZBYCZg8VBAoyMDExLTAzLTI4AjExGe2UhOuhnOyVvOq1rCAzMOyjvOuFhCAuLi4k7Jet64yAIEtCTyDstJ3snqzrpbwg67mE66Gv7ZWY7JesLi4uZAIDD2QWAmYPFQQKMjAxNC0wMy0yOAIxNBcgS0JPLeuMgO2VnOyVvOq1rO2YkS4uLhINCgkNCgkJDQoJCQkNCgkuLi5kAgMPZBYCAgMPZBYeAgEPFgIfAAUPMjAxNi4wMy4yNyjsnbwpZAICD2QWLmYPDxYCHghJbWFnZVVybAVDaHR0cDovL2ltYWdlLmtvcmVhYmFzZWJhbGwuY29tL2NsaWVudC9pbWFnZXMvc2NoZWR1bGUvaWNvbl9sb3NlLmdpZmRkAgEPDxYEHg1BbHRlcm5hdGVUZXh0BQbroa/rjbAfAgVJaHR0cDovL2ltYWdlLmtvcmVhYmFzZWJhbGwuY29tL2NsaWVudC9pbWFnZXMvY29tbW9uL2VtYmxlbS9lbWJsZW1CX0xULnBuZ2RkAgIPFgIfAAUPM+yKuSAxMe2MqCAz66y0ZAIDDw8WAh8CBUJodHRwOi8vaW1hZ2Uua29yZWFiYXNlYmFsbC5jb20vY2xpZW50L2ltYWdlcy9zY2hlZHVsZS9pY29uX3dpbi5naWZkZAIEDw8WBB8DBQJrdB8CBUlodHRwOi8vaW1hZ2Uua29yZWFiYXNlYmFsbC5jb20vY2xpZW50L2ltYWdlcy9jb21tb24vZW1ibGVtL2VtYmxlbUJfS1QucG5nZGQCBQ8WAh8ABQ8xMOyKuSA17YyoIDHrrLRkAgYPFgIfAAUG66Gv642wZAIHDxYCHwECDBYYZg9kFgJmDxUBATBkAgEPZBYCZg8VAQEwZAICD2QWAmYPFQEBMGQCAw9kFgJmDxUBATFkAgQPZBYCZg8VAQEwZAIFD2QWAmYPFQEBMGQCBg9kFgJmDxUBATBkAgcPZBYCZg8VAQEwZAIID2QWAmYPFQEBMmQCCQ9kFgJmDxUBAS1kAgoPZBYCZg8VAQEtZAILD2QWAmYPFQEBLWQCCA8WAh8ABQEzZAIJDxYCHwAFAThkAgoPFgIfAAUBMWQCCw8WAh8ABQE0ZAIMDxYCHwAFAmt0ZAINDxYCHwECDBYYZg9kFgJmDxUBATBkAgEPZBYCZg8VAQEwZAICD2QWAmYPFQEBMmQCAw9kFgJmDxUBATJkAgQPZBYCZg8VAQEwZAIFD2QWAmYPFQEBMWQCBg9kFgJmDxUBATBkAgcPZBYCZg8VAQEwZAIID2QWAmYPFQEBLWQCCQ9kFgJmDxUBAS1kAgoPZBYCZg8VAQEtZAILD2QWAmYPFQEBLWQCDg8WAh8ABQE1ZAIPDxYCHwAFAThkAhAPFgIfAAUBMWQCEQ8WAh8ABQEzZAISDxYCHwAFBuyImOybkGQCEw8WAh8ABQU3LDg2M2QCFA8WAh8ABQUxMjo1OGQCFQ8WAh8ABQUxNTo1NWQCFg8WAh8ABQQyOjU3ZAIDDxYCHwECChYUZg9kFgJmDxUCCeqysOyKue2DgAbsl4bsnYxkAgEPZBYCZg8VAgbtmYjrn7Ai6rmA7IKs7JewNu2YuCg07ZqMMuygkCDroIjsnbzrpqwpIGQCAg9kFgJmDxUCBzPro6jtg4AU6rmA7J6s7JygKDntmowpIA0KDQpkAgMPZBYCZg8VAgcy66Oo7YOAJOq5gOyDge2YhCg07ZqMKSDsnKTsmpTshK0oNu2ajCkgDQoNCmQCBA9kFgJmDxUCBuyLpOyxhSTroIjsnbzrpqwoM+2ajCkg7Ius7Jqw7KSAKDftmowpIA0KDQpkAgUPZBYCZg8VAgbrj4Tro6gU7J207Jes7IOBKDftmowpIA0KDQpkAgYPZBYCZg8VAgnrs5HsgrTtg4AU66y46rec7ZiEKDftmowpIA0KDQpkAgcPZBYCZg8VAgbtj63tiKwX66CI7J2866asMigzIDTtmowpIA0KDQpkAggPZBYCZg8VAgbrs7Ttgawh66CI7J2866asKDHtmowpIO2UvOuFuCg17ZqMKSANCg0KZAIJD2QWAmYPFQIG7Ius7YyQJ+q5gOyEseyyoCDquYDsnbXsiJgg64KY6rSR64KoIOuwleyiheyyoGQCBA8WAh8ABTs8aDQgY2xhc3M9ImJ1bCBoX2x0Ij7roa/rjbAg7J6Q7J207Ja47LigIO2DgOyekCDquLDroZ08L2g0PmQCBQ8WAh8ABWc8dHI+PHRoIHNjb3BlPSJyb3ciIGNvbHNwYW49JzE1Jz5UT1RBTDwvdGg+PHRkPjMzPC90ZD48dGQ+ODwvdGQ+PHRkPjM8L3RkPjx0ZD4zPC90ZD48dGQ+MC4yNjg8L3RkPjwvdHI+ZAIGDxYCHwECDhYcZg9kFgZmDxUPATED7KSRCeq5gOusuO2YuAbtiKzrlYUGJm5ic3A7BDPruYQGJm5ic3A7BuyCvOynhAYmbmJzcDsG7KSR67mEBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBNAEwATABMAUwLjI2M2QCAQ9kFgZmDxUPATED7YOACeq5gOyjvO2YhAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BuyCrOq1rAYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMTY3ZAICD2QWBmYPFQ8BMgPsp4AJ66y46rec7ZiEBuyCvOynhAYmbmJzcDsGJm5ic3A7BDLrlYUEMeu5hAYmbmJzcDsEMuuzkQYmbmJzcDsG7KKM7JWIBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATUBMQEwATAFMC4yMjJkAgMPZBYGZg8VDwEzA+ycoAnsmKTsirntg50G7IK87KeEBiZuYnNwOwYmbmJzcDsJ7Jqw7KSR7JWIBiZuYnNwOwbsoozslYgGJm5ic3A7BuyCvOynhAbspJHruYQGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBNQEyATABMQUwLjM1MGQCBA9kFgZmDxUPATQD5LiACeuwleyiheycpAYmbmJzcDsEM+2MjAYmbmJzcDsG7Jqw7JWIBiZuYnNwOwbsgrzsp4QGJm5ic3A7Buykkeu5hAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBNAExATABMAUwLjIzM2QCBQ9kFgZmDxUPATQD5LiJCeq5gOuMgOulmQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMTU0ZAIGD2QWBmYPFQ8BNQPsoowJ67CV7ZeM64+EBiZuYnNwOwQy67mEBiZuYnNwOwnspJHtnazruYQGJm5ic3A7BDTqtawGJm5ic3A7BuyCvOynhAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMgEwATEBMAUwLjA4M2QCBw9kFgZmDxUPATYG5LiJ5LiACeyGkOyaqeyEnQYmbmJzcDsG7KKM7JWIBiZuYnNwOwbsnKDrlYUGJm5ic3A7BuycoOu5hAYmbmJzcDsGJm5ic3A7BuyCrOq1rAYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEzATEBMAExBTAuMzI0ZAIID2QWBmYPFQ8BNwPsmrAJ7Jik7ZiE6re8BiZuYnNwOwQx65WFBiZuYnNwOwYmbmJzcDsEMuuVhQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMgEwATABMAUwLjMzM2QCCQ9kFgZmDxUPATcD7YOACeq5gOuMgOyasAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BuyijOu5hAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATABMAEwBTAuMjczZAIKD2QWBmYPFQ8BNwPsmrAJ6rmA7J6s7JygBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsE7JqwMwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATEBMQExBTAuMjUwZAILD2QWBmYPFQ8BOAPkuowJ7J207Jes7IOBBiZuYnNwOwYmbmJzcDsEMuuVhQYmbmJzcDsG7KKM7JWIBiZuYnNwOwbsnKDsi6QGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEzATEBMAEwBTAuMTg4ZAIMD2QWBmYPFQ8BOAPtg4AJ7J207Jqw66+8BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsEM+2MjAYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATABMAEwBTAuMzkxZAIND2QWBmYPFQ8BOQPtj6wJ7JWI7KSR7Je0BiZuYnNwOwYmbmJzcDsEMe2MjAYmbmJzcDsG7KSR7JWIBiZuYnNwOwQ06rWsBiZuYnNwOwnsmrDtnazruYQGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMgExATEBMAUwLjIxNGQCBw8WAh8ABS48aDQgY2xhc3M9ImJ1bCBoX2t0Ij5rdCB3aXog7YOA7J6QIOq4sOuhnTwvaDQ+ZAIIDxYCHwAFZzx0cj48dGggc2NvcGU9InJvdyIgY29sc3Bhbj0nMTUnPlRPVEFMPC90aD48dGQ+MzE8L3RkPjx0ZD44PC90ZD48dGQ+NDwvdGQ+PHRkPjU8L3RkPjx0ZD4wLjI2NzwvdGQ+PC90cj5kAgkPFgIfAQIRFiJmD2QWBmYPFQ8BMQPkuowJ67CV6rK97IiYBDTqtawGJm5ic3A7BDLrlYUG7KKM67mEBiZuYnNwOwYmbmJzcDsG7IK87KeEBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwEwATABMAUwLjIwMGQCAQ9kFgZmDxUPATED7KSRCeuwsOuzkeyYpQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMTY3ZAICD2QWBmYPFQ8BMgPsoowJ7J2064yA7ZiVBuycoOuVhQYmbmJzcDsG7Yis65WFBiZuYnNwOwbtiKzrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMAEwATAFMC4zMjVkAgMPZBYGZg8VDwEyA+yijAntlZjspIDtmLgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsG7Jyg65WFBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMQEwATABMAUwLjM1MGQCBA9kFgZmDxUPATMD7KSRCeycoO2VnOykgAbtiKzrlYUGJm5ic3A7BuyasOyViAYmbmJzcDsEM+uVhQYmbmJzcDsG7KKM67mEBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBNAExATEBMAUwLjM3NWQCBQ9kFgZmDxUPATMD5LqMCeygleuLpOyatAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMDAwZAIGD2QWBmYPFQ8BNAPsp4AJ66eI66W07YWMBuyCvOynhAYmbmJzcDsG7Yis65WFBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATIBMAEwATAFMC4zNDZkAgcPZBYGZg8VDwE0Bu2DgOyngAnsnbTsp4TsmIEGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7Bu2IrOu5hAYmbmJzcDsGJm5ic3A7BuyijOyViAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMgExATABMAUwLjEyNWQCCA9kFgZmDxUPATQD7KO8Ceq5gOuvvO2YgQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMTgyZAIJD2QWBmYPFQ8BNQPkuIAJ6rmA7IOB7ZiEBiZuYnNwOwQy65WFBiZuYnNwOwTsoowyBiZuYnNwOwQ06rWsBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATIBMQEwATEFMC4zMzNkAgoPZBYGZg8VDwE1BuyjvOS4iQnquYDsl7Dtm4gGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7CeyijOykkeyViAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMQExATABMQUwLjI5NmQCCw9kFgZmDxUPATYD7Y+sCeycpOyalOyErQYmbmJzcDsG7Jyg65WFBiZuYnNwOwQx7YyMBiZuYnNwOwTsmrAyBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMQEwATAFMC40NzhkAgwPZBYGZg8VDwE2BuyjvOycoAnsi6zsmrDspIAGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BuycoOu5hAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMQEwATABMAUwLjI0MmQCDQ9kFgZmDxUPATcD7JqwCeq5gOyCrOyXsAYmbmJzcDsEMeyngQYmbmJzcDsG7KKM7ZmIBiZuYnNwOwnspJHtnazruYQGJm5ic3A7BuyCvOynhAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwExATMBMQUwLjI0NmQCDg9kFgZmDxUPATgG5LiJ5LiACeusuOyDgeyyoAYmbmJzcDsGJm5ic3A7BDTqtawG7IK87KeEBiZuYnNwOwQx7YyMBiZuYnNwOwbsnKDrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMAEwATEFMC4yNjhkAg8PZBYGZg8VDwE5A+ycoAnrsJXquLDtmIEGJm5ic3A7BiZuYnNwOwbtiKzslYgG7Jqw7JWIBiZuYnNwOwbsgrzsp4QGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwEyATABMQUwLjM4MWQCEA9kFgZmDxUPATkD7Y+sCeq5gOyiheuvvAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMDMzZAIKDxYCHwAFOzxoNCBjbGFzcz0iYnVsIGhfbHQiPuuhr+uNsCDsnpDsnbTslrjsuKAg7Yis7IiYIOq4sOuhnTwvaDQ+ZAILDxYCHwAFpAE8dHI+PHRoIHNjb3BlPSJyb3ciIGNvbHNwYW49IjYiPlRPVEFMPC90aD48dGQ+ODwvdGQ+PHRkPjM1PC90ZD48dGQ+MTQzPC90ZD48dGQ+MzE8L3RkPjx0ZD44PC90ZD48dGQ+MTwvdGQ+PHRkPjM8L3RkPjx0ZD41PC90ZD48dGQ+NTwvdGQ+PHRkPjQ8L3RkPjx0ZD42LjIzPC90ZD48L3RyPmQCDA8WAh8BAgYWDGYPZBYKZg8VAwnroIjsnbzrpqwG7ISg67CcA+2MqGQCAQ8VAwEwATEBMGQCAg8VCgE0AjE5AjcwAjE3ATUBMQEyATIBNAEzZAIDDxUBBDIuNzBkAgQPFQEENi43NWQCAQ9kFgpmDxUDCeq5gOycoOyYgQM1LjIGJm5ic3A7ZAIBDxUDATABMAEwZAICDxUKATEBMwIxNQEzATABMAEwATABMAEwZAIDDxUBBDIuMjVkAgQPFQEEMC4wMGQCAg9kFgpmDxUDCeuwleynhO2YlQM2LjUGJm5ic3A7ZAIBDxUDATABMAEwZAICDxUKBTEgMS8zATYCMzQBNAExATABMQEyATEBMWQCAw8VAQQyLjQ1ZAIEDxUBBDYuNzVkAgMPZBYKZg8VAwnsnbTrqoXsmrADNy4yBiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgMxLzMBMQEyATEBMAEwATABMAEwATBkAgMPFQEEMC4wMGQCBA8VAQQwLjAwZAIED2QWCmYPFQMJ7KCV64yA7ZiEAzcuMwYmbmJzcDtkAgEPFQMBMAEwATBkAgIPFQoDMS8zATEBMwExATABMAEwATABMAEwZAIDDxUBBDIuMDhkAgQPFQEEMC4wMGQCBQ9kFgpmDxUDCeq5gOyEseuwsAM4LjQGJm5ic3A7ZAIBDxUDATABMAEwZAICDxUKATEBNQIxOQE1ATIBMAEwATEBMAEwZAIDDxUBBDQuNTBkAgQPFQEEMC4wMGQCDQ8WAh8ABS48aDQgY2xhc3M9ImJ1bCBoX2t0Ij5rdCB3aXog7Yis7IiYIOq4sOuhnTwvaDQ+ZAIODxYCHwAFpAE8dHI+PHRoIHNjb3BlPSJyb3ciIGNvbHNwYW49IjYiPlRPVEFMPC90aD48dGQ+OTwvdGQ+PHRkPjM5PC90ZD48dGQ+MTM5PC90ZD48dGQ+MzM8L3RkPjx0ZD44PC90ZD48dGQ+MDwvdGQ+PHRkPjQ8L3RkPjx0ZD42PC90ZD48dGQ+MzwvdGQ+PHRkPjM8L3RkPjx0ZD4zLjg3PC90ZD48L3RyPmQCDw8WAh8BAgUWCmYPZBYKZg8VAwbtlLzrhbgG7ISg67CcA+yKuWQCAQ8VAwExATIBMGQCAg8VCgE2AjI1Ajg4AjIzATYBMAExATQBMQExZAIDDxUBBDYuMjBkAgQPFQEEMS41MGQCAQ9kFgpmDxUDCeyhsOustOq3vAM3LjgGJm5ic3A7ZAIBDxUDATABMAEyZAICDxUKATIBNwIzMwE2ATABMAExATIBMAEwZAIDDxUBBDQuNzBkAgQPFQEEMC4wMGQCAg9kFgpmDxUDCeqzoOyYge2RnAM5LjYGJm5ic3A7ZAIBDxUDATABMAEwZAICDxUKAzEvMwEzATYBMgExATABMQEwATIBMmQCAw8VAQQzLjg2ZAIEDxUBBTU0LjAwZAIDD2QWCmYPFQMJ6rmA7J6s7JykAzkuOQbtmYDrk5xkAgEPFQMBMAExATFkAgIPFQoDMS8zATEBMgEwATABMAEwATABMAEwZAIDDxUBBDAuMDBkAgQPFQEEMC4wMGQCBA9kFgpmDxUDCe2ZjeyEseyaqQM5LjED7IS4ZAIBDxUDATABMAExZAICDxUKAzEvMwEzAjEwATIBMQEwATEBMAEwATBkAgMPFQEEMC4wMGQCBA8VAQQwLjAwZGQFGPf+OConLpqF7v74c0DA52QR0j50+SFLvk+zgcbR8Q==" />
</div>

<script type="text/javascript">
//&lt;![CDATA[
var theForm = document.forms['mainForm'];
if (!theForm) {
    theForm = document.mainForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]&gt;
</script>


<script src="/WebResource.axd?d=m0cHWOoLqlcgDn6qjzDaMjcjDDU64JCjYFzzb8ecw_2CsjhNwqV8uTKcyDzyxGq2vHEClPn4t_FxPcFBU0DpmoKhSr20QxJ_p8CVDLn04QQ1&amp;t=635803002500000000" type="text/javascript"></script>


<script src="/ScriptResource.axd?d=ESBzuf4QpYS-0918gCqJShjtsO-rU4WOlwNHeYM70cruOBTfVGD0MwN8EcL0TSDR0B9JpSB_YrwJhm7hd0hSDjtuUOR7ooD_uY0EyCGhA3K-0ZFr2qvq7U1TLWMIOiUZv7Yyal-6j1gxqkDCm5vM-OzSJzQL6qo3cMHBSOjFZ7aL33ljlmb4uzzQq1pOPLOY0&amp;t=5f9d5645" type="text/javascript"></script>
<script type="text/javascript">
//&lt;![CDATA[
if (typeof(Sys) === 'undefined') throw new Error('ASP.NET Ajax 클라이언트 쪽 프레임워크를 로드하지 못했습니다.');
//]]&gt;
</script>

<script src="/ScriptResource.axd?d=wDArcqEI8jZYz_yIpnVwC6Tl6LkxO4cqyYkwoq7_JnQzGplUMZHfzFGRLJQUIv5lzyDKX3ObXw54k-jnApfOZ1t3AZyp5nJvymae74vgOJt9uY-e1GUIAZXpvIAHUkx4lyhFh08JXR4bfaupKXDcYnKkd_pm1sovxA5lEzQWoTYKI_LpvL2lGH5xESGGoks10&amp;t=5f9d5645" type="text/javascript"></script>
<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="A5085B47" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAAJbIZcqOG+bAM9HLmVRdN+9EG4FQbqeMQMc81CqbOAKu9JnIcVRYJcBJWbTZPYa3MUxuv6NFF/ddPT7IDd7ctPX" />
</div>
        <div id="wrap">
	        <!-- header -->

	        <div id="header">
		        <div class="row ">
			        <div class="top_area">
				        <ul class="top_menu">
					        <li class="first-child"><a href="/" title="home"><img src="//image.koreabaseball.com/client/images/common/btn_home.png" alt="home" /></a></li>

					            <li><a href="/Member/Login.aspx" title="로그인">로그인</a></li>
					            <li><a href="/Member/Join/Accessterms.aspx" title="회원가입">회원가입</a></li>

					        <li class="last"><a href="//eng.koreabaseball.com/" title="ENGLISH">ENGLISH</a></li>
				        </ul>
				        <span class="srch_player">
                            <input name="ctl00$ctl00$txtSearchWord" type="text" id="txtSearchWord" placeholder="선수검색" class="input01" />
					        <input type="image" alt="선수검색하기" src="//image.koreabaseball.com/client/images/common/btn_srch.png" class="btn_srch" onclick="setPlayerSearch();return false;" />
				        </span>
			        </div>
		        </div>
		        <div class="row">
			        <div class="wrapper03">

				        <h1 class="logo"><a href="/Default.aspx">KBO</a></h1>
                        <div class="kbo_history mgt30">
					        <div class="row">
					            <span class="title"><b>KBO</b> 역사속 오늘 | </span>
					            <span class="date">3월 28일</span>
					        </div>
					        <div class="row flow_text bg_black mgt10">
						        <ul id="HistoryItem" style="position: relative; overflow: hidden; white-space: nowrap;"><li style="position: relative; display: inline; top: 0px; left: -34px;"><a href="/Etc/TodayHistory.aspx?searchDate=1988-03-28"><span class="point">88'</span> <b>이웅희 총재 추대 ...</b> 플라자 호텔에서 열린 구단주...</a> </li><li style="position: relative; display: inline; top: 0px; left: -34px;"><a href="/Etc/TodayHistory.aspx?searchDate=2001-03-28"><span class="point">01'</span> <b>한국야구인명사전 발...</b> </a> </li><li style="position: relative; display: inline; top: 0px; left: -34px;"><a href="/Etc/TodayHistory.aspx?searchDate=2011-03-28"><span class="point">11'</span> <b>프로야구 30주년 ...</b> 역대 KBO 총재를 비롯하여...</a> </li><li style="position: relative; display: inline; top: 0px; left: -34px;"><a href="/Etc/TodayHistory.aspx?searchDate=2014-03-28"><span class="point">14'</span> <b> KBO-대한야구협...</b>



	...</a> </li></ul>
						        <div class="btnControl">
							        <a href="#" class="left"><img src="//image.koreabaseball.com/client/images/main/roll_prev.png" alt="Left" /></a>
							        <a href="#" class="stop"><img src="//image.koreabaseball.com/client/images/main/roll_stop.png" alt="Stop" /></a>
							        <a href="#" class="right"><img src="//image.koreabaseball.com/client/images/main/roll_next.png" alt="Right" /></a>
						        </div>
					        </div>
				        </div>
			        </div>

		        </div>
		        <div class="row">
			        <div class="wrapper03">
                        <!-- gnb -->
				        <div class="gnb">
					        <ul class="main">
						        <li><a href="/Schedule/ScoreBoard/ScoreBoard.aspx" style="width:86px">경기일정/결과</a>
							        <ul class="sub por01">
								        <li><a href="/Schedule/ScoreBoard/ScoreBoard.aspx">스코어보드</a></li>
								        <li><a href="/Schedule/GameList/General.aspx?seriesId=1">경기일정/결과</a></li>
                                        <li><a href="/Schedule/GameList/CalendarSchedule.aspx">월별일정/결과</a></li>


							        </ul>
						        </li>
						        <li><a href="/TeamRank/TeamRank.aspx">팀순위</a>
							        <ul class="sub">

In [65]:
soup = BeautifulSoup(html,'lxml')

In [105]:
#team = soup.find('table',{'class':'socreBoard'}).findAll('th',{'scope':'row'})
#score = soup.find('table',{'class':'soncreBoard'}).findAll('td')
#tr = soup.select('table.socreBoard tr')
tr=soup.select('table.socreBoard tr:nth-of-type(2)')
for row in tr:
    print row

<tr>
<th scope="row">롯데</th>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td class="point">3</td>
<td class="hit">8</td>
<td class="hit">1</td>
<td class="hit">4</td>
</tr>

In [104]:
tr

[<tr>
 <th scope="col">TEAM</th>
 <th scope="col">1</th><th scope="col">2</th><th scope="col">3</th><th scope="col">4</th><th scope="col">5</th><th scope="col">6</th>
 <th scope="col">7</th><th scope="col">8</th><th scope="col">9</th><th scope="col">10</th><th scope="col">11</th><th scope="col">12</th>
 <th scope="col">R</th><th scope="col">H</th><th scope="col">E</th><th scope="col">B</th>
 </tr>]

In [83]:
print score[1].text

0

In [76]:
print hName

[<th scope="row">롯데</th>, <th scope="row">kt</th>]