In [1]:
#-*- coding: utf-8 -*- 
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By

from BoxScoreParser import BoxScoreParser
import numpy  as np
import pandas as pd
import random as rd
import time
import urllib2
import sys

In [58]:
reload(sys)
sys.setdefaultencoding('utf-8')

In [7]:
browser = webdriver.Chrome(executable_path='/home/gohyunyoung98/바탕화면/Github/kbo_parsing/chromedriver')

browser.get('http://www.koreabaseball.com/Schedule/ScoreBoard/ScoreBoard.aspx')
for i in range(3):
    browser.find_element_by_id('cphContainer_cphContents_btnPreDate').click()
    time.sleep(1)

time.sleep(1)
#a href 태그가 "/Schdule..."로 시작하는 elements수집
btnList = browser.find_elements_by_css_selector('a[href^="/Schedule/Game/BoxScore.aspx?"]')
for i in range(len(btnList)):
    browser.find_elements_by_css_selector('a[href^="/Schedule/Game/BoxScore.aspx?"]')[i].click()
    time.sleep(1)
            
    html = browser.page_source
    soup = BeautifulSoup(html,'lxml')
    
    hName = soup.findAll('table.socreBoard th')
        
    browser.get('http://www.koreabaseball.com/Schedule/ScoreBoard/ScoreBoard.aspx')
    for i in range(3):
        browser.find_element_by_id('cphContainer_cphContents_btnPreDate').click()
        time.sleep(1)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"cphContainer_cphContents_btnPreDate"}
  (Session info: chrome=49.0.2623.110)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-34-generic x86_64)

In [8]:
print html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><link rel="shortcut icon" href="//image.koreabaseball.com/client/images/common/favicon.ico" /><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta name="keywords" content="kbo" /><meta name="author-date" content="20130308" /><meta http-equiv="x-ua-compatible" content="IE=9, Chrome" /><title>
	박스스코어 | 경기일정/결과 | KBO
</title><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/reset.css?version=201503111" /><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/common.css?version=20160310" /><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/jquery-ui.css" /><link type="text/css" rel="stylesheet" href="//image.koreabaseball.com/client/css/jquery.bxslider.css?version=20151006" />

	<script async="" src="//www.google-analytics.com/analytics.js"></script><script type="text/javascript" src="//image.koreabaseball.com/client/js/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="//image.koreabaseball.com/client/js/jquery-ui.js"></script>
	<script type="text/javascript" src="//image.koreabaseball.com/client/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="//image.koreabaseball.com/client/js/common.js?version=20150724"></script>
    <script type="text/javascript" src="//image.koreabaseball.com/client/js/rolling.js?version=20150305"></script>

    <link type="text/css" rel="stylesheet" href="http://image.koreabaseball.com/client/css/jquery-ui-theme.css?version=20150317" />
    <link type="text/css" rel="stylesheet" href="http://image.koreabaseball.com/client/css/sub.css?version=20150311" />
    <link type="text/css" rel="stylesheet" href="http://image.koreabaseball.com/client/css/games.css?version=20151029" />




    <script type="text/javascript">
        function setPlayerSearch() {
            var searchWord = encodeURI($('#txtSearchWord').val());

            if (searchWord != "") {
                location.href = "/Player/Search.aspx?searchWord=" + searchWord;
            }
        }
    </script>
    <script type="text/javascript">
        (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-15700655-14', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
    <form method="post" action="./BoxScore.aspx?leagueId=1&amp;seriesId=1&amp;gameId=20160327NCWO0&amp;gyear=2016" id="mainForm">
<div class="aspNetHidden">
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJNDA4MTc2ODc1D2QWAmYPZBYCZg9kFgICAw9kFgYCAQ8WAh4EVGV4dAUKM+yblCAzMOydvGQCAg8WAh4LXyFJdGVtQ291bnQCBhYMZg9kFgJmDxUECjE5ODUtMDMtMzACODUZ7Yyo64SM7Yq466CI7J207IqkIOqwnOuniSDsgrzshLE1OjMg7ZW07YOcKOuMgOq1rCksIOyCvC4uLmQCAQ9kFgJmDxUECjIwMDQtMDMtMzACMDQX7ZWcLeuvuC3snbwgM+q1rSDsu6QuLi4s7ZWc6rWt7JW86rWs7JyE7JuQ7ZqMIOuwleyaqeyYpCDstJ3snqzripQuLi5kAgIPZBYCZg8VBAoyMDA4LTAzLTMwAjA4He2MqOuEjO2KuOugiOydtOyKpCDqsJzrp4kgLi4uIuuRkOyCsDQ6MSDtnojslrTroZzspogo7J6g7IukKQ0uLi5kAgMPZBYCZg8VBAoyMDExLTAzLTMwAjExG+yImOybkOyLnCwg7ZSE66Gc7JW86rWsIC4uLijsiJjsm5Dsi5zqsIAg7ZSE66Gc7JW86rWsIOygnDEw6rWs64uoLi4uZAIED2QWAmYPFQQKMjAxMS0wMy0zMAIxMRntlITroZzslbzqtawgMzDso7zrhYQgLi4uLu2VnOq1reyVvOq1rOychOybkO2ajOuKlCDtlZzqta3siqTtj6zsuKDsgqwuLi5kAgUPZBYCZg8VBAoyMDEzLTAzLTMwAjEzFzIwMTMg7ZWc6rWt7JW87L+g66W0Li4uHuusuO2VmSBMRy1TSywg7IKs7KeBIO2VnO2ZlC4uLmQCAw9kFgICAw9kFh4CAQ8WAh8ABQ8yMDE2LjAzLjI3KOydvClkAgIPZBYuZg8PFgIeCEltYWdlVXJsBUJodHRwOi8vaW1hZ2Uua29yZWFiYXNlYmFsbC5jb20vY2xpZW50L2ltYWdlcy9zY2hlZHVsZS9pY29uX3dpbi5naWZkZAIBDw8WBB4NQWx0ZXJuYXRlVGV4dAUCTkMfAgVJaHR0cDovL2ltYWdlLmtvcmVhYmFzZWJhbGwuY29tL2NsaWVudC9pbWFnZXMvY29tbW9uL2VtYmxlbS9lbWJsZW1CX05DLnBuZ2RkAgIPFgIfAAUOOOyKuSA47YyoIDHrrLRkAgMPDxYCHwIFQ2h0dHA6Ly9pbWFnZS5rb3JlYWJhc2ViYWxsLmNvbS9jbGllbnQvaW1hZ2VzL3NjaGVkdWxlL2ljb25fbG9zZS5naWZkZAIEDw8WBB8DBQbrhKXshLwfAgVJaHR0cDovL2ltYWdlLmtvcmVhYmFzZWJhbGwuY29tL2NsaWVudC9pbWFnZXMvY29tbW9uL2VtYmxlbS9lbWJsZW1CX1dPLnBuZ2RkAgUPFgIfAAUPNeyKuSAxMO2MqCAx66y0ZAIGDxYCHwAFAk5DZAIHDxYCHwECDBYYZg9kFgJmDxUBATFkAgEPZBYCZg8VAQEzZAICD2QWAmYPFQEBM2QCAw9kFgJmDxUBATBkAgQPZBYCZg8VAQEwZAIFD2QWAmYPFQEBMGQCBg9kFgJmDxUBATFkAgcPZBYCZg8VAQEwZAIID2QWAmYPFQEBMGQCCQ9kFgJmDxUBAS1kAgoPZBYCZg8VAQEtZAILD2QWAmYPFQEBLWQCCA8WAh8ABQE4ZAIJDxYCHwAFAjE3ZAIKDxYCHwAFATBkAgsPFgIfAAUBMWQCDA8WAh8ABQbrhKXshLxkAg0PFgIfAQIMFhhmD2QWAmYPFQEBMGQCAQ9kFgJmDxUBATJkAgIPZBYCZg8VAQExZAIDD2QWAmYPFQEBMGQCBA9kFgJmDxUBATBkAgUPZBYCZg8VAQEwZAIGD2QWAmYPFQEBMGQCBw9kFgJmDxUBATBkAggPZBYCZg8VAQEwZAIJD2QWAmYPFQEBLWQCCg9kFgJmDxUBAS1kAgsPZBYCZg8VAQEtZAIODxYCHwAFATNkAg8PFgIfAAUBOGQCEA8WAh8ABQExZAIRDxYCHwAFATNkAhIPFgIfAAUG6rOg7LKZZAITDxYCHwAFBTMsNDc2ZAIUDxYCHwAFBTEzOjAwZAIVDxYCHwAFBTE1OjQ0ZAIWDxYCHwAFBDI6NDRkAgMPFgIfAQILFhZmD2QWAmYPFQIJ6rKw7Iq57YOAJeuCmOyEseuylCgx7ZqMIDLsgqzshJwg7Jqw7JuUIO2ZiOufsClkAgEPZBYCZg8VAgbtmYjrn7Bm64KY7ISx67KUM+2YuCgx7ZqMMeygkCDrsJXso7ztmIQpIOuwleuPmeybkDPtmLgoMu2ajDLsoJAg7J207J6s7ZWZKSDsnbTtmLjspIA07Zi4KDftmowx7KCQIOuniOygleq4uCkgZAICD2QWAmYPFQIHM+ujqO2DgBTquYDshLHsmrEoMu2ajCkgDQoNCmQCAw9kFgJmDxUCBzLro6jtg4Ak6rmA7YOc6rWwKDPtmowpIOqwleuvvOq1rSg57ZqMKSANCg0KZAIED2QWAmYPFQIG7Iuk7LGFFOydtO2Dneq3vCgz7ZqMKSANCg0KZAIFD2QWAmYPFQIJ64+E66Oo7J6QFOydtO2Dneq3vCgx7ZqMKSANCg0KZAIGD2QWAmYPFQIJ7KO866Oo7IKsJOuwleyEneuvvCgz7ZqMKSDsnbTsnqzsnKgoNe2ajCkgDQoNCmQCBw9kFgJmDxUCCeqyrOygnOyCrBTrsJXsoJXsnYwoOO2ajCkgDQoNCmQCCA9kFgJmDxUCCeuzkeyCtO2DgDTrjIDri4jrj4goNe2ajCkg67CV64+Z7JuQKDbtmowpIOyEnOqxtOywvSg37ZqMKSANCg0KZAIJD2QWAmYPFQIG7Y+t7YisFOydtOyerO2VmSgz7ZqMKSANCg0KZAIKD2QWAmYPFQIG7Ius7YyQJ+2ZqeyduO2DnCDstpTtj4ntmLgg6rmA7KSA7Z2sIOyghOydvOyImGQCBA8WAh8ABTc8aDQgY2xhc3M9ImJ1bCBoX25jIj5OQyDri6TsnbTrhbjsiqQg7YOA7J6QIOq4sOuhnTwvaDQ+ZAIFDxYCHwAFaDx0cj48dGggc2NvcGU9InJvdyIgY29sc3Bhbj0nMTUnPlRPVEFMPC90aD48dGQ+NDI8L3RkPjx0ZD4xNzwvdGQ+PHRkPjg8L3RkPjx0ZD44PC90ZD48dGQ+MC4yNzI8L3RkPjwvdHI+ZAIGDxYCHwECEhYkZg9kFgZmDxUPATED5LqMCeuwleuvvOyasAQy67mEBuyasOyViAbsmrDslYgGJm5ic3A7BDLsp4EGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATQBMgEyATEFMC4zMjdkAgEPZBYGZg8VDwExBu2DgOyasAnquYDspIDsmYQGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BDHrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATEBMAEwATAFMC4xMDBkAgIPZBYGZg8VDwEyBuyijOyasAnquYDshLHsmrEG7IK87KeEBOykkTMEM+uVhQYmbmJzcDsGJm5ic3A7BuyCvOynhAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQE0ATEBMgExBTAuMjk3ZAIDD2QWBmYPFQ8BMgPtg4AJ7Jyk67OR7Zi4BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwQz7KeBBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATABMAEwBTAuMDgzZAIED2QWBmYPFQ8BMgPkuowJ7Zmp7Jyk7Zi4BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATABMAEwATAFMC4wMDBkAgUPZBYGZg8VDwEzA+yasAnrgpjshLHrspQG7Jqw7ZmIBuyijOyViAYmbmJzcDsEM+yngQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMgEyATEFMC4zMjdkAgYPZBYGZg8VDwEzBu2DgOyijAnquYDsooXtmLgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwbsnKDrlYUGJm5ic3A7BiZuYnNwOwbsnKDruYQGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMgEwATABMAUwLjI1OGQCBw9kFgZmDxUPATQD5LiACe2FjOyehOymiAbsmrDslYgG7KKM67mEBiZuYnNwOwbsgrzsp4QGJm5ic3A7BDHrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBNAExATABMAUwLjE1OGQCCA9kFgZmDxUPATQD5LiACeyhsO2Pie2YuAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BuyijOyViAYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATEBMAEwBTAuMTY3ZAIJD2QWBmYPFQ8BNQPkuIkJ67CV7ISd66+8BuyijOyViAYmbmJzcDsG7KKM7JWIBuykkeu5hAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMgEwATAFMC40MjlkAgoPZBYGZg8VDwE1A+ycoAnqsJXrr7zqta0GJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsEMuuVhQYmbmJzcDsE7KKMMgYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEyATEBMAEwBTAuMzE2ZAILD2QWBmYPFQ8BNgPsp4AJ7J207Zi47KSABuyCvOynhAYmbmJzcDsJ7Jyg7KKM7JWIBiZuYnNwOwQ06rWsBiZuYnNwOwbspJHtmYgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEzATIBMQEyBTAuMzEzZAIMD2QWBmYPFQ8BNgPtg4AJ7KGw7JiB7ZuIBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsG7IK87KeEBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATEBMAEwATAFMC4xNzRkAg0PZBYGZg8VDwE3A+ykkQnsnbTsooXsmrEGJm5ic3A7BuyCvOynhAbtiKzrlYUGJm5ic3A7BuyasOyViAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwExATABMAUwLjM0OWQCDg9kFgZmDxUPATcG7KO87KSRCeydtOyerOycqAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwbsmrDruYQGJm5ic3A7BDLrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMgEwATABMAUwLjIxN2QCDw9kFgZmDxUPATgG7Jyg5LiJCeyngOyEne2biAYmbmJzcDsEM+uVhQnsmrDspJHslYgGJm5ic3A7BuyCvOynhAYmbmJzcDsG7Jqw67mEBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBNAExATEBMQUwLjIwN2QCEA9kFgZmDxUPATkD7Y+sCeq5gO2DnOq1sAYmbmJzcDsG7KSR7JWIBOyasDIGJm5ic3A7BuyijOyViAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwEzATABMgUwLjM2N2QCEQ9kFgZmDxUPATkD7Y+sCeyaqeuNle2VnAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsG7Yis65WFBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATABMAEwBTAuMTg4ZAIHDxYCHwAFOzxoNCBjbGFzcz0iYnVsIGhfd28iPuuEpeyEvCDtnojslrTroZzspogg7YOA7J6QIOq4sOuhnTwvaDQ+ZAIIDxYCHwAFZzx0cj48dGggc2NvcGU9InJvdyIgY29sc3Bhbj0nMTUnPlRPVEFMPC90aD48dGQ+MzE8L3RkPjx0ZD44PC90ZD48dGQ+MzwvdGQ+PHRkPjM8L3RkPjx0ZD4wLjI0NjwvdGQ+PC90cj5kAgkPFgIfAQIVFipmD2QWBmYPFQ8BMQPkuowJ7ISc6rG07LC9BDLruYQGJm5ic3A7BuyasOyViAYmbmJzcDsENOq1rAYmbmJzcDsEMeuzkQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMQEwATEFMC4yNDRkAgEPZBYGZg8VDwExA+S6jAnquYDsp4DsiJgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMAEwATABMAUwLjAwMGQCAg9kFgZmDxUPATID7KSRCeqzoOyiheyasQbsgrzsp4QGJm5ic3A7BuyijOu5hAYmbmJzcDsG7Jyg67mEBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEzATABMAEwBTAuMjkzZAIDD2QWBmYPFQ8BMgPtiKwJ6rmA7IOB7IiYBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATABMAEwATAFMC4wMDBkAgQPZBYGZg8VDwEyA+2IrAnrp4jsoJXquLgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMAEwATABMAUwLjAwMGQCBQ9kFgZmDxUPATID7YisCeq5gO2Dne2YlQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEwATABMAEwBTAuMDAwZAIGD2QWBmYPFQ8BMgPtg4AJ7ZmN7ISx6rCRBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwQy65WFBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATABMAEwBTAuMjUwZAIHD2QWBmYPFQ8BMgPtiKwJ7J2067O06re8BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATABMAEwATAFMC4wMDBkAggPZBYGZg8VDwEzA+yasAnsnbTtg53qt7wG7KSR7JWIBiZuYnNwOwQ06rWsBiZuYnNwOwbslbzshKAGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATIBMQEwATAFMC4yNjJkAgkPZBYGZg8VDwEzA+yasAntl4jsoJXtmJEGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BDPrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATEBMAEwATAFMC4zMzNkAgoPZBYGZg8VDwE0A+yijAnrjIDri4jrj4gGJm5ic3A7BuyijOu5hAbsgqzqtawGJm5ic3A7BDLrs5EGJm5ic3A7BiZuYnNwOwbsmrDslYgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATMBMQEwATAFMC4zNzVkAgsPZBYGZg8VDwE0BuyjvOyijAnrsJXsoJXsnYwGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMAEwATABMAUwLjE0OGQCDA9kFgZmDxUPATUD5LiJCeq5gOuvvOyEsQYmbmJzcDsEM+uVhQbsmrDslYgGJm5ic3A7BiZuYnNwOwbsoozslYgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwEyATEBMAUwLjMwNmQCDQ9kFgZmDxUPATUG7KO85LiJCeyepeyYgeyEnQYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BDPrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMQEwATABMAUwLjI1MGQCDg9kFgZmDxUPATYD5LiACeycpOyEneuvvAYmbmJzcDsG7KSR7JWIBuyCvOynhAYmbmJzcDsGJm5ic3A7BuyCvOynhAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEzATEBMAExBTAuMjYyZAIPD2QWBmYPFQ8BNgPkuIAJ7ISc64+Z7JqxBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsEMuuVhQYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQExATABMAEwBTAuNDAwZAIQD2QWBmYPFQ8BNwPtj6wJ67CV64+Z7JuQBiZuYnNwOwbsooztmYgGJm5ic3A7BDHtjIwGJm5ic3A7BDLrs5EGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwExATIBMQUwLjMzM2QCEQ9kFgZmDxUPATcD7Y+sCeq5gOyerO2YhAYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BDPrlYUGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMQEwATABMAUwLjA4M2QCEg9kFgZmDxUPATgG7KeA7KSRCeyehOuzkeyasQYmbmJzcDsG7IK87KeEBiZuYnNwOwbsgrzsp4QGJm5ic3A7BiZuYnNwOwQy65WFBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgEPFQMGJm5ic3A7BiZuYnNwOwYmbmJzcDtkAgIPFQUBMwEwATABMAUwLjE0M2QCEw9kFgZmDxUPATkD7JygCeq5gO2VmOyEsQYmbmJzcDsGJm5ic3A7BuyCvOynhAbsgrzsp4QGJm5ic3A7BiZuYnNwOwbsoozslYgGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAQ8VAwYmbmJzcDsGJm5ic3A7BiZuYnNwO2QCAg8VBQEzATEBMAEwBTAuMTQzZAIUD2QWBmYPFQ8BOQPsnKAJ7J6l7Iuc7JykBiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7BiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAIBDxUDBiZuYnNwOwYmbmJzcDsGJm5ic3A7ZAICDxUFATABMAEwATAFMC4yNzhkAgoPFgIfAAU3PGg0IGNsYXNzPSJidWwgaF9uYyI+TkMg64uk7J2064W47IqkIO2IrOyImCDquLDroZ08L2g0PmQCCw8WAh8ABaQBPHRyPjx0aCBzY29wZT0icm93IiBjb2xzcGFuPSI2Ij5UT1RBTDwvdGg+PHRkPjk8L3RkPjx0ZD4zNDwvdGQ+PHRkPjExOTwvdGQ+PHRkPjMxPC90ZD48dGQ+ODwvdGQ+PHRkPjE8L3RkPjx0ZD4zPC90ZD48dGQ+NzwvdGQ+PHRkPjM8L3RkPjx0ZD4zPC90ZD48dGQ+NC41MzwvdGQ+PC90cj5kAgwPFgIfAQIGFgxmD2QWCmYPFQMJ7J207J6s7ZWZBuyEoOuwnAPsirlkAgEPFQMBMgEyATBkAgIPFQoBNAIxOAI2MwIxNgE1ATEBMgE2ATMBM2QCAw8VAQQ0LjU4ZAIEDxUBBDYuNzVkAgEPZBYKZg8VAwnqtazssL3rqqgDNS4xBiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgExATQCMTgBMwEwATABMQEwATABMGQCAw8VAQQ0LjkxZAIEDxUBBDAuMDBkAgIPZBYKZg8VAwnquYDshKDqt5wDNi41BiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgExATMCMTABMwExATABMAExATABMGQCAw8VAQQ2Ljc1ZAIEDxUBBDAuMDBkAgMPZBYKZg8VAwnqsJXsnqXsgrADNy44BiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgExATMCMTEBMwExATABMAEwATABMGQCAw8VAQQzLjg2ZAIEDxUBBDAuMDBkAgQPZBYKZg8VAwnrsJXspIDsmIEDOC4yBiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgExATMCMTEBMwExATABMAEwATABMGQCAw8VAQQxLjY5ZAIEDxUBBDAuMDBkAgUPZBYKZg8VAwnrsJXrr7zshJ0DOS41BiZuYnNwO2QCAQ8VAwExATABMWQCAg8VCgExATMBNgEzATABMAEwATABMAEwZAIDDxUBBDAuMDBkAgQPFQEEMC4wMGQCDQ8WAh8ABTs8aDQgY2xhc3M9ImJ1bCBoX3dvIj7rhKXshLwg7Z6I7Ja066Gc7KaIIO2IrOyImCDquLDroZ08L2g0PmQCDg8WAh8ABaUBPHRyPjx0aCBzY29wZT0icm93IiBjb2xzcGFuPSI2Ij5UT1RBTDwvdGg+PHRkPjk8L3RkPjx0ZD40MzwvdGQ+PHRkPjE2MjwvdGQ+PHRkPjQyPC90ZD48dGQ+MTc8L3RkPjx0ZD4yPC90ZD48dGQ+MTwvdGQ+PHRkPjc8L3RkPjx0ZD44PC90ZD48dGQ+ODwvdGQ+PHRkPjQuNzA8L3RkPjwvdHI+ZAIPDxYCHwECBRYKZg9kFgpmDxUDCeuwleyjvO2YhAbshKDrsJwD7YyoZAIBDxUDATABMQEwZAICDxUKBTIgMi8zAjE4AjYzAjE4AjExATEBMAEzATcBN2QCAw8VAQQ3LjI3ZAIEDxUBBTIzLjYzZAIBD2QWCmYPFQMJ6rmA7IOB7IiYAzMuMQYmbmJzcDtkAgEPFQMBMQExATBkAgIPFQoFMyAxLzMCMTMCNTcCMTIBMwEwATEBMwEwATBkAgMPFQEEMS4zOGQCBA8VAQQwLjAwZAICD2QWCmYPFQMJ66eI7KCV6ri4AzcuNQYmbmJzcDtkAgEPFQMBMAEwATBkAgIPFQoBMQE0ATkBNAExATEBMAEwATEBMWQCAw8VAQQyLjU3ZAIEDxUBBDkuMDBkAgMPZBYKZg8VAwnquYDtg53tmJUDOC45BiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgExATMCMTQBMwEwATABMAEwATABMGQCAw8VAQQwLjAwZAIEDxUBBDAuMDBkAgQPZBYKZg8VAwnsnbTrs7Tqt7wDOS4zBiZuYnNwO2QCAQ8VAwEwATABMGQCAg8VCgExATUCMTkBNQEyATABMAExATABMGQCAw8VAQQxLjgwZAIEDxUBBDAuMDBkZHsZzuBKVl8VQx58wk/Mw4r03fMw9EqRl0U205DPXP8U" />
</div>

<script type="text/javascript">
//&lt;![CDATA[
var theForm = document.forms['mainForm'];
if (!theForm) {
    theForm = document.mainForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]&gt;
</script>


<script src="/WebResource.axd?d=m0cHWOoLqlcgDn6qjzDaMjcjDDU64JCjYFzzb8ecw_2CsjhNwqV8uTKcyDzyxGq2vHEClPn4t_FxPcFBU0DpmoKhSr20QxJ_p8CVDLn04QQ1&amp;t=635803002500000000" type="text/javascript"></script>


<script src="/ScriptResource.axd?d=ESBzuf4QpYS-0918gCqJShjtsO-rU4WOlwNHeYM70cruOBTfVGD0MwN8EcL0TSDR0B9JpSB_YrwJhm7hd0hSDjtuUOR7ooD_uY0EyCGhA3K-0ZFr2qvq7U1TLWMIOiUZv7Yyal-6j1gxqkDCm5vM-OzSJzQL6qo3cMHBSOjFZ7aL33ljlmb4uzzQq1pOPLOY0&amp;t=5f9d5645" type="text/javascript"></script>
<script type="text/javascript">
//&lt;![CDATA[
if (typeof(Sys) === 'undefined') throw new Error('ASP.NET Ajax 클라이언트 쪽 프레임워크를 로드하지 못했습니다.');
//]]&gt;
</script>

<script src="/ScriptResource.axd?d=wDArcqEI8jZYz_yIpnVwC6Tl6LkxO4cqyYkwoq7_JnQzGplUMZHfzFGRLJQUIv5lzyDKX3ObXw54k-jnApfOZ1t3AZyp5nJvymae74vgOJt9uY-e1GUIAZXpvIAHUkx4lyhFh08JXR4bfaupKXDcYnKkd_pm1sovxA5lEzQWoTYKI_LpvL2lGH5xESGGoks10&amp;t=5f9d5645" type="text/javascript"></script>
<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="A5085B47" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAAJCNgC8cTs7No6nkzSP6lgfEG4FQbqeMQMc81CqbOAKu/dio5L57VXVfcgKpPboVTGlxuFg7+vciqsVQD9k64/2" />
</div>
        <div id="wrap">
	        <!-- header -->

	        <div id="header">
		        <div class="row ">
			        <div class="top_area">
				        <ul class="top_menu">
					        <li class="first-child"><a href="/" title="home"><img src="//image.koreabaseball.com/client/images/common/btn_home.png" alt="home" /></a></li>

					            <li><a href="/Member/Login.aspx" title="로그인">로그인</a></li>
					            <li><a href="/Member/Join/Accessterms.aspx" title="회원가입">회원가입</a></li>

					        <li class="last"><a href="//eng.koreabaseball.com/" title="ENGLISH">ENGLISH</a></li>
				        </ul>
				        <span class="srch_player">
                            <input name="ctl00$ctl00$txtSearchWord" type="text" id="txtSearchWord" placeholder="선수검색" class="input01" />
					        <input type="image" alt="선수검색하기" src="//image.koreabaseball.com/client/images/common/btn_srch.png" class="btn_srch" onclick="setPlayerSearch();return false;" />
				        </span>
			        </div>
		        </div>
		        <div class="row">
			        <div class="wrapper03">

				        <h1 class="logo"><a href="/Default.aspx">KBO</a></h1>
                        <div class="kbo_history mgt30">
					        <div class="row">
					            <span class="title"><b>KBO</b> 역사속 오늘 | </span>
					            <span class="date">3월 30일</span>
					        </div>

In [9]:
print browser.current_url

http://www.koreabaseball.com/Schedule/Game/BoxScore.aspx?leagueId=1&seriesId=1&gameId=20160327NCWO0&gyear=2016

In [10]:
boxScoreParser = BoxScoreParser(browser.current_url)

In [4]:
tr=soup.select('table.socreBoard tr:nth-of-type(2)')
for x in tr:
    y=x.text.split()
    z=y[1]
    
z

u'0'

In [12]:
x=x.split()

TypeError: 'NoneType' object is not callable

In [34]:
ClassScenario = pd.read_csv('./ClassScenario.csv',index_col=0)

In [35]:
ClassScenario

,context,original
class,,
1,?이 선발로 등판한 ?은 ?과의 경기에서 ?-?점으로 승리했다. 경기의 승패에 결정...,장원준이 선발로 등판한 두산은 삼성과의 한국시리즈 3차전 경기에서 5-1점으로 승리...
1,?은 ?일 ?에서 열린 ?와 맞대결에서 ?-?으로 승리했다. ?은 ?회초 ?사 ?에...,삼성은 3일 잠실구장에서 열린 '2015 타이어뱅크 KBO리그' LG 트윈스와 시즌...
1,?은 ?일 ?에서 열린 ?와 경기에서 ?은 ?회말 ?의 끝내기 안타로 ?-? 짜릿한...,삼성은 10일 대구에서 열린 KIA와 '2015 타이어뱅크 KBO 리그' 홈 경기에...
1,?는 ?일 ?에서 열린 ?와의 경기에서 ?-?로 승리했다. 이날 선발투수로 나온 ?...,NC 다이노스는 11일 창원 마산야구장에서 열린 2015 KBO리그 SK 와이번스와...
1,넥센은 11일 목동구장에서 열린 '2015 타이어뱅크 KBO 리그' kt wiz와의...,넥센은 11일 목동구장에서 열린 '2015 타이어뱅크 KBO 리그' kt wiz와의...
1,삼성은 15일 대전 한화생명이글스파크서 열린 2015 타이어뱅크 KBO리그 한화와의...,삼성은 15일 대전 한화생명이글스파크서 열린 2015 타이어뱅크 KBO리그 한화와의...
2,"두산은 30일 열린 한국시리즈 4차전 경기에서 삼성을 4:3, 1점차로 간신히 꺾으...","두산은 30일 열린 한국시리즈 4차전 경기에서 삼성을 4:3, 1점차로 간신히 꺾으..."
2,"SK는 1일 열린 두산과의 홈 경기에서 1-2, 한점차이로 석패했다. SK는 김광현...","SK는 1일 열린 두산과의 홈 경기에서 1-2, 한점차이로 석패했다. SK는 김광현..."
2,한화 이글스가 극적인 승부를 펼치고도 눈앞에서 승리를 놓쳤다. 한화는 10일 사직구...,한화 이글스가 극적인 승부를 펼치고도 눈앞에서 승리를 놓쳤다. 한화는 10일 사직구...
3,한화가 연장 끝내기 승리로 함박웃음을 지었다. 한화 이글스는 7일 대전 한화생명이글...,한화가 연장 끝내기 승리로 함박웃음을 지었다. 한화 이글스는 7일 대전 한화생명이글...
3,LG는 8일 대전 한화생명 이글스파크에서 열린 2015 타이어뱅크 KBO리그 한화 ...,LG는 8일 대전 한화생명 이글스파크에서 열린 2015 타이어뱅크 KBO리그 한화 ...
3,삼성은 9일 대구에서 열린 롯데 자이언츠와의 홈경기서 3-4로 뒤진 9회말 박석민의...,삼성은 9일 대구에서 열린 롯데 자이언츠와의 홈경기서 3-4로 뒤진 9회말 박석민의...
4,유희관을 선발로 앞세운 두산은 31일 열린 한국시리즈 5차전 경기에서 장원삼이 나선...,유희관을 선발로 앞세운 두산은 31일 열린 한국시리즈 5차전 경기에서 장원삼이 나선...
4,삼성은 27일 열린 한국시리즈 2차전 경기에서 1-6점으로 크게 패하며 홈 팬들을 ...,삼성은 27일 열린 한국시리즈 2차전 경기에서 1-6점으로 크게 패하며 홈 팬들을 ...
4,삼성은 1일 오후 6시 30분 수원 케이티 위즈 파크에서 열린 kt wiz와의 '2...,삼성은 1일 오후 6시 30분 수원 케이티 위즈 파크에서 열린 kt wiz와의 '2...
4,"홈런왕 박병호(29, 넥센 히어로즈)가 잠실에서 홈런 2개를 몰아치는 괴력을 과시...","홈런왕 박병호(29, 넥센 히어로즈)가 잠실에서 홈런 2개를 몰아치는 괴력을 과시..."
4,LG는 11일 잠실구장에서 열린 두산 베어스와의 시즌 2차전 경기에서 6-9로 패했...,LG는 11일 잠실구장에서 열린 두산 베어스와의 시즌 2차전 경기에서 6-9로 패했...
5,5일 열린 2015 타이어뱅크 프로야구 경기에서 스튜어트를 등판시킨 NC와 정대현이...,5일 열린 2015 타이어뱅크 프로야구 경기에서 스튜어트를 등판시킨 NC와 정대현이...
6,롯데는 3일 부산 사직구장서 열린 2015 타이어뱅크 KBO리그 두산과의 시즌 첫 ...,롯데는 3일 부산 사직구장서 열린 2015 타이어뱅크 KBO리그 두산과의 시즌 첫 ...
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN
NaN,NaN,NaN

In [41]:
ClassList = ClassScenario.get_value(index=1,col='context')

In [44]:
for x in ClassList:
    print x

?이 선발로 등판한 ?은 ?과의 경기에서 ?-?점으로 승리했다. 경기의 승패에 결정적인 영향을 미친 키 플레이어는 ?였다.
?은 ?일 ?에서 열린 ?와 맞대결에서 ?-?으로 승리했다. ?은 ?회초 ?사 ?에서 ?(이)가 ? 마무리투수 ?과 승부에서 승리했다. ?의 ?가 혈투에 마침표를 찍었다.
?은 ?일 ?에서 열린 ?와 경기에서 ?은 ?회말 ?의 끝내기 안타로 ?-? 짜릿한 승리를 거뒀다.
?는 ?일 ?에서 열린 ?와의 경기에서 ?-?로 승리했다. 이날 선발투수로 나온 ?은 ?이닝 동안 ?피안타 ?탈삼진 ?실점(?자책)을 기록해 승리투수가 됐다. 뒤이어 등장한 이민호도 ?이닝 ?피안타 ?탈삼진 ?실점으로 ? 타선을 잘 막아냈다.
넥센은 11일 목동구장에서 열린 '2015 타이어뱅크 KBO 리그' kt wiz와의 경기에서 타선이 kt 선발 크리스 옥스프링에게 꽁꽁 묶이면서 4-6으로 패했다. 넥센은 kt가 안방에서 창단 첫 승을 기록하는 모습을 지켜봐야 했다.
삼성은 15일 대전 한화생명이글스파크서 열린 2015 타이어뱅크 KBO리그 한화와의 경기에서 이승엽의 결승 스리런 홈런에 힘입어 8-3으로 이겼다. 이날 삼성은 선발 타일러 클로이드를 필두로 박근홍, 안지만, 권오준이 이어 던졌고, 한화는 선발 유창식에 이어 김기현, 송창식, 박정진, 정대훈, 김민우가 마운드에 올랐다.

In [54]:
a = BoxScoreParser('a')